In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('advertising.csv')

In [4]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [6]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [7]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [8]:
df.shape

(200, 4)

In [9]:
df.sample(15)

TV  Radio  Newspaper  Sales
140   73.4   17.0       12.9   10.9
79   116.0    7.7       23.1   11.0
99   135.2   41.7       45.9   17.2
110  225.8    8.2       56.5   13.4
83    68.4   44.5       35.6   13.6
10    66.1    5.8       24.2    8.6
7    120.2   19.6       11.6   13.2
72    26.8   33.0       19.3    8.8
187  191.1   28.7       18.2   17.3
33   265.6   20.0        0.3   17.4
182   56.2    5.7       29.7    8.7
28   248.8   27.1       22.9   18.9
161   85.7   35.8       49.3   13.3
86    76.3   27.5       16.0   12.0
147  243.2   49.0       44.3   25.4

In [10]:
###plt.figure(figsize=(50,30))
###plt.xticks(rotation=90)
###ax = sns.countplot(x=df['TV']);


In [11]:
x = df[['TV','Radio','Newspaper']]
y = df.Sales

In [12]:
x.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [13]:
x.shape

(200, 3)

In [14]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [15]:
y.shape

(200,)

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

#### %25 train_test_split 

In [17]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 16)

In [18]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((150, 3), (50, 3), (150,), (50,))

In [19]:
lr = LinearRegression()
regmodel = lr.fit(x_train, y_train)
y_pred = regmodel.predict(x_test)
y_pred

array([15.5549848 , 20.35523898, 13.81408235, 18.16021812, 13.97128516,
        7.49543199,  9.95052655, 12.19880572,  9.16353953,  7.71141801,
       10.1090945 , 12.73483506, 20.36470635, 11.74821994,  8.54208936,
       14.64218688, 10.42571856, 17.08700445,  9.4679562 , 13.83965441,
        9.74661266, 14.31331074, 16.44676231, 15.40977715, 21.68572631,
       20.57454409, 10.69674048, 20.38531972, 14.05174436, 17.81167466,
       19.28397313, 14.20103219, 10.66147876, 16.86420823, 18.16205212,
        6.14841118, 12.60778612, 19.18365841,  5.46104984, 15.30699712,
       15.15413067,  5.50580246, 16.03296603, 20.31828138, 12.56354549,
       23.92407011, 10.21013138, 10.86980867, 18.00364683, 12.17871341])

In [20]:
mean_squared_error(y_pred, y_test)**0.5

1.524047627612448

In [21]:
r2_score(y_pred,y_test)

0.88460090582618

#### %18 train_test_split 

In [22]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x, y, test_size = 0.18, random_state = 16)

In [23]:
x1_train.shape, x1_test.shape, y1_train.shape, y1_test.shape

((164, 3), (36, 3), (164,), (36,))

In [24]:
lr = LinearRegression()
regmodel1 = lr.fit(x1_train, y1_train)
y_pred1 = regmodel1.predict(x1_test)
y_pred1

array([15.46257194, 20.44711556, 13.70899377, 18.0852167 , 13.84962823,
        7.38332523,  9.87661305, 12.09613311,  9.11850399,  7.62127458,
        9.97982764, 12.60709209, 20.31516991, 11.79491943,  8.50568794,
       14.60111637, 10.34568591, 17.02917825,  9.32539953, 13.82779313,
        9.65280124, 14.31084482, 16.36077515, 15.50497892, 21.65864009,
       20.59599203, 10.56560741, 20.38359443, 13.97132317, 17.8739591 ,
       19.37941713, 14.12926685, 10.5985583 , 16.88566928, 18.16679692,
        6.04354262])

In [25]:
mean_squared_error(y_pred1, y1_test)**0.5

1.3508291760175075

In [26]:
r2_score(y_pred1,y1_test)

0.8994318025876881

In [27]:
y_pred1

array([15.46257194, 20.44711556, 13.70899377, 18.0852167 , 13.84962823,
        7.38332523,  9.87661305, 12.09613311,  9.11850399,  7.62127458,
        9.97982764, 12.60709209, 20.31516991, 11.79491943,  8.50568794,
       14.60111637, 10.34568591, 17.02917825,  9.32539953, 13.82779313,
        9.65280124, 14.31084482, 16.36077515, 15.50497892, 21.65864009,
       20.59599203, 10.56560741, 20.38359443, 13.97132317, 17.8739591 ,
       19.37941713, 14.12926685, 10.5985583 , 16.88566928, 18.16679692,
        6.04354262])

In [28]:
x.mean()

TV           147.0425
Radio         23.2640
Newspaper     30.5540
dtype: float64

## TV advertising is the best sales method.